config/routes.rb
Rails.application.routes.draw do

  root 'resumes#show' #'pages#homepage'
  get '/resume' => 'resumes#show'
  get '/cv' => redirect('/resume')

  namespace :admin do
    root 'dashboard#show', as: :dashboard

    resources :images
    get '/login' => 'sessions#new', as: :login
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy', as: :logout
  end

end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                :integer          not null, primary key
#  key               :string           not null
#  file_file_name    :string
#  file_content_type :string
#  file_file_size    :integer
#  file_updated_at   :datetime
#  created_at        :datetime
#  updated_at        :datetime
#

class Image < ActiveRecord::Base
  before_save { self.key = key.downcase }
  validates :key, presence: true, uniqueness: true
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  before_action :authenticate_user!

  def index
    @images = Image.paginate(pages: params[:pages])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to @image, notice: 'Image was successfully uploaded'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def image_params
      params.require(:image).permit(:file, :key)
    end
end

app/views/admin/images/index.html.slim
h1 Images
- if @images.any?
  .row
    .col-md-8.col-md-offset-2
      = will_paginate
      .container
        .table
          .row
            .col-md-10
              | Key
          - (@images || []).each do |image|
            .row
              .col-md-10= image.key
              .col-md-2= link_to 'Delete', image, method: :delete, class: 'delete'
      = will_paginate
- else
  .center.jumbotron
    h2
      | You haven't uploaded any images yet.
    = link_to 'Add one now!', new_admin_image_path, class: 'btn btn-large btn-primary'