config/routes.rb
Rails.application.routes.draw do

  root 'resumes#show' #'pages#homepage'
  get '/resume' => 'resumes#show'
  get '/cv' => redirect('/resume')

  namespace :admin do
    root 'dashboard#show', as: :dashboard

    resources :images
    get '/login' => 'sessions#new', as: :login
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy', as: :logout
  end

end

app/views/layouts/_admin_nav.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    nav
      ul.nav.navbar-nav.navbar-right
        li
          - if logged_in?
            = link_to 'Log out', admin_logout_path, method: :delete
          - else
            = link_to 'Log in', admin_login_path

app/views/layouts/_ie_shim.html.slim
/[if lt IE 9]
  script src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js'

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta name='viewport' content='width=device-width, initial-scale=1'

    title DigitalResume
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/ie_shim'
  body
    = render 'layouts/admin_nav'
    .container
      - flash.each do |type, message|
        .alert[class="alert-#{type}"]
          = message

      = yield

    - if Rails.env.development?
      = debug params
      = debug flash

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name='viewport' content='width=device-width, initial-scale=1'

    title= full_title
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    = yield :head

  body
    .container
      header
        div.header
          | [ Tim Woodbury ]
      .contents
        = yield